object Form2: TForm2
  Left = 0
  Top = 0
  Caption = #1043#1088#1072#1092#1080#1082
  ClientHeight = 225
  ClientWidth = 295
  Color = clSilver
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  OnCreate = FormCreate
  OnPaint = FormPaint
  OnResize = FormResize
  PixelsPerInch = 96
  TextHeight = 13
end
